# Deployment to staging
name: Manually triggered deployment to STAGING
on:
  workflow_dispatch:

env:
  DOCKER_MEM_LIMIT: '4G'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2    
    
      # Set up Java
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          
      # Build
      - name: Build with Maven
        # mvn: no progress bars, n. of threads = 1.0x n. of cores
        run: |
          mvn --batch-mode --threads 1.0C clean compile package

      # Build the Docker image
      - name: Build backend
        run: |-
          docker build \
          --memory $DOCKER_MEM_LIMIT \
          --tag "rk/rukovoditel:latest" \
          --tag "rk/rukovoditel:$GITHUB_SHA" \
          --file Dockerfile
          .
