# Deployment to staging
name: Manually triggered deployment to STAGING
on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.commit }}!"
          echo "- in ${{ github.event.inputs.tag }}!"
