name: Maven Package
on:
# runs tests for commits pushed to master
  push:
    branches: [ master ]
    # do not run tests if file README.md changes
    
    paths-ignore:
      - 'README.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.

  pull_request:
    branches: [ master ]

    paths-ignore:
      - 'README.md'

  schedule:
    # run tests every day at 12 am and 12 pm UTC
   - cron:  '0 */12 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Build
        run: mvn -B clean package -DskipTests
      - name: Run tests
        run: mvn -B clean verify -Pheadless-mode
